// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq9if7Ls4j_fCBCuC22EFmMeMx3ceMxrc',
    appId: '1:432446569056:web:aa863cd0aadb3cf5386105',
    messagingSenderId: '432446569056',
    projectId: 'ecommerce-63e7c',
    authDomain: 'ecommerce-63e7c.firebaseapp.com',
    storageBucket: 'ecommerce-63e7c.appspot.com',
    measurementId: 'G-NY2NL8S49H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvCxP81W85MLHhkhlrj5Y5R4qq1347Rc',
    appId: '1:432446569056:android:e6fbc3a228f2f15a386105',
    messagingSenderId: '432446569056',
    projectId: 'ecommerce-63e7c',
    storageBucket: 'ecommerce-63e7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxdtl6c1xwIo6xd-05kq21NV0_zNxMjs',
    appId: '1:432446569056:ios:a0917ea0d9542e2a386105',
    messagingSenderId: '432446569056',
    projectId: 'ecommerce-63e7c',
    storageBucket: 'ecommerce-63e7c.appspot.com',
    androidClientId: '432446569056-2urjhkoh7t42m0qj9q5p6v5k6ema4ja7.apps.googleusercontent.com',
    iosClientId: '432446569056-f3vip5uq9f0b2nrnj9upiojguhl8ndmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomm',
  );

}